"""initial migration

Revision ID: 1e754db7cbd1
Revises: 
Create Date: 2025-12-17 17:38:26.263224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e754db7cbd1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('Folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('total_size', sa.BigInteger(), nullable=True),
    sa.Column('user_token', sa.String(length=256), nullable=True),
    sa.Column('vector_table_uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_token'], ['auth_tokens.token'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vector_table_uuid')
    )
    op.create_table('Files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('updated_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['Folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_files_folder_id', 'Files', ['folder_id'], unique=False)
    op.create_index('idx_files_folder_name', 'Files', ['folder_id', 'file_name'], unique=False)
    op.create_index('idx_files_upload_time', 'Files', ['upload_time'], unique=False, postgresql_using='btree', postgresql_ops={'upload_time': 'DESC'})
    op.create_table('FileIndices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.String(length=255), nullable=False),
    sa.Column('vector_store_table', sa.String(length=255), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('chunk_overlap', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('num_chunks', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['Files.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['Folders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index('idx_fileindices_file_id', 'FileIndices', ['file_id'], unique=False)
    op.create_index('idx_fileindices_folder_id', 'FileIndices', ['folder_id'], unique=False)
    op.create_index('idx_fileindices_status', 'FileIndices', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fileindices_status', table_name='FileIndices')
    op.drop_index('idx_fileindices_folder_id', table_name='FileIndices')
    op.drop_index('idx_fileindices_file_id', table_name='FileIndices')
    op.drop_table('FileIndices')
    op.drop_index('idx_files_upload_time', table_name='Files', postgresql_using='btree', postgresql_ops={'upload_time': 'DESC'})
    op.drop_index('idx_files_folder_name', table_name='Files')
    op.drop_index('idx_files_folder_id', table_name='Files')
    op.drop_table('Files')
    op.drop_table('Folders')
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
