
"""Format smoke tests -- for every programmatically generable allowlisted
format, run real docling parsing and retrieve the content back.

Each format generates a minimal sample carrying a sentinel string, runs
DocumentConverter.convert, and asserts the sentinel is in the output. Catches
"allowlisted but the parser dependency is missing" breakage. Needs docling
parsers + LibreOffice but no DB/GPU model; PDF/image OCR and audio are out of
scope.
"""

import shutil
import subprocess
import zipfile
from pathlib import Path

import pytest

SENT = "哨兵內容SENTINEL"

_SOFFICE = shutil.which("soffice")


@pytest.fixture(scope="module")
def samples(tmp_path_factory):
    """Generate all programmatically constructible minimal samples; legacy/template variants only if LibreOffice is present."""
    S = tmp_path_factory.mktemp("fmt")

    def w(name, text):
        (S / name).write_text(text, encoding="utf-8")

    # Pure-parser text family
    w("t.md", f"# 標題\n\n{SENT}\n")
    w("t.qmd", f"---\ntitle: x\n---\n\n{SENT}\n")
    w("t.rmd", f"---\ntitle: x\n---\n\n{SENT}\n")
    for ext in ("adoc", "asciidoc", "asc"):
        w(f"t.{ext}", f"= T\n\n{SENT}\n")
    w("t.html", f"<html><body><p>{SENT}</p></body></html>")
    w("t.htm", f"<html><body><p>{SENT}</p></body></html>")
    w("t.xhtml", f'<?xml version="1.0"?><html xmlns="http://www.w3.org/1999/xhtml"><body><p>{SENT}</p></body></html>')
    for ext in ("tex", "latex"):
        w(f"t.{ext}", f"\\documentclass{{article}}\\begin{{document}}{SENT}\\end{{document}}")
    w("t.vtt", f"WEBVTT\n\n00:00.000 --> 00:02.000\n{SENT}\n")
    w("t.eml", f"From: a@b.c\nTo: d@e.f\nSubject: test\nContent-Type: text/plain; charset=utf-8\n\n{SENT}\n")

    # Office Open XML family (generated by python-docx / openpyxl; variants are isomorphic renames)
    import docx as _docx
    d = _docx.Document(); d.add_paragraph(SENT); d.save(S / "t.docx")
    for ext in ("dotx", "docm", "dotm"):
        shutil.copy(S / "t.docx", S / f"t.{ext}")
    import openpyxl
    wb = openpyxl.Workbook(); wb.active["A1"] = SENT; wb.save(S / "t.xlsx")
    shutil.copy(S / "t.xlsx", S / "t.xlsm")

    # epub (minimal zip)
    with zipfile.ZipFile(S / "t.epub", "w") as z:
        z.writestr("mimetype", "application/epub+zip", compress_type=zipfile.ZIP_STORED)
        z.writestr("META-INF/container.xml", '<?xml version="1.0"?><container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/></rootfiles></container>')
        z.writestr("OEBPS/content.opf", '<?xml version="1.0"?><package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="id"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>t</dc:title><dc:identifier id="id">x</dc:identifier><dc:language>zh</dc:language></metadata><manifest><item id="c" href="c.xhtml" media-type="application/xhtml+xml"/></manifest><spine><itemref idref="c"/></spine></package>')
        z.writestr("OEBPS/c.xhtml", f'<?xml version="1.0"?><html xmlns="http://www.w3.org/1999/xhtml"><body><p>{SENT}</p></body></html>')

    # OpenDocument (minimal ODF; needs odfdo -- this is where a missing dependency turns red)
    def odf(name, mime, body):
        with zipfile.ZipFile(S / name, "w") as z:
            z.writestr("mimetype", mime, compress_type=zipfile.ZIP_STORED)
            z.writestr("META-INF/manifest.xml", f'<?xml version="1.0"?><manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" manifest:version="1.2"><manifest:file-entry manifest:full-path="/" manifest:media-type="{mime}"/><manifest:file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/></manifest:manifest>')
            z.writestr("content.xml", body)
    _T = '<?xml version="1.0"?><office:document-content xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0" xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0" office:version="1.2"><office:body>{}</office:body></office:document-content>'
    odf("t.odt", "application/vnd.oasis.opendocument.text",
        _T.format(f'<office:text><text:p>{SENT}</text:p></office:text>'))
    odf("t.ods", "application/vnd.oasis.opendocument.spreadsheet",
        _T.format(f'<office:spreadsheet><table:table table:name="S"><table:table-row><table:table-cell office:value-type="string"><text:p>{SENT}</text:p></table:table-cell></table:table-row></table:table></office:spreadsheet>'))
    odf("t.odp", "application/vnd.oasis.opendocument.presentation",
        _T.format(f'<office:presentation><draw:page draw:name="p1"><draw:frame><draw:text-box><text:p>{SENT}</text:p></draw:text-box></draw:frame></draw:page></office:presentation>'))

    # Legacy Office (needs soffice; skip that batch of cases if not installed)
    if _SOFFICE:
        def conv(to, src):
            subprocess.run([_SOFFICE, "--headless", "--convert-to", to, str(S / src),
                            "--outdir", str(S)], capture_output=True, timeout=120)
        conv("doc", "t.docx"); conv("dot", "t.docx")
        conv("xls", "t.xlsx"); conv("xlt", "t.xlsx")
        conv("ppt", "t.odp"); conv("pot", "t.odp"); conv("pps", "t.odp")
        # pptx family: soffice produces pptx; macro/show variants are isomorphic renames (potx cannot be opened in practice, so it is excluded)
        conv("pptx", "t.odp"); conv("ppsx", "t.odp"); conv("pptm", "t.odp")
        if (S / "t.pptx").exists():
            for ext in ("potm", "ppsm"):
                shutil.copy(S / "t.pptx", S / f"t.{ext}")
    return S


@pytest.fixture(scope="module")
def converter(itest_db):
    # itest_db serves only as the opt-in gate (RAG_RUN_DB_ITESTS); the converter itself does not use a DB
    from docling.document_converter import DocumentConverter
    return DocumentConverter()


_PURE_PARSER_EXTS = [
    "md", "qmd", "rmd", "adoc", "asciidoc", "asc",
    "html", "htm", "xhtml", "tex", "latex", "vtt", "eml",
    "docx", "dotx", "docm", "dotm", "xlsx", "xlsm",
    "epub", "odt", "ods", "odp",
]
_LEGACY_EXTS = ["doc", "dot", "xls", "xlt", "ppt", "pot", "pps",
                "pptx", "ppsx", "pptm", "potm", "ppsm"]


@pytest.mark.parametrize("ext", _PURE_PARSER_EXTS)
def test_pure_parser_format(samples, converter, ext):
    text = converter.convert(str(samples / f"t.{ext}")).document.export_to_markdown()
    assert SENT in text, f".{ext} 解析結果不含哨兵內容"


@pytest.mark.skipif(not _SOFFICE, reason="LibreOffice(soffice)未安裝")
@pytest.mark.parametrize("ext", _LEGACY_EXTS)
def test_legacy_office_format(samples, converter, ext):
    f = samples / f"t.{ext}"
    assert f.exists(), f"soffice 轉檔未產出 t.{ext}"
    text = converter.convert(str(f)).document.export_to_markdown()
    assert SENT in text, f".{ext} 解析結果不含哨兵內容"


# BL-05: verify provenance meta-shape (meta.headings, doc_items[].prov[].page_no)
# against real docling output, so a docling upgrade that drifts the chunk schema
# turns these cases red.

class _LenTok:
    def encode(self, text, add_special_tokens=False):
        return list(text)


def test_chunk_records_carry_headings_md(samples, converter):
    """md through the real HierarchicalChunker -> the record's headings are non-empty (# heading)."""
    from docling.chunking import HierarchicalChunker
    from src.domain.rag.docling_loader import _refine_chunks_for_token_budget

    doc = converter.convert(str(samples / "t.md")).document
    chunks = list(HierarchicalChunker().chunk(doc))
    recs = _refine_chunks_for_token_budget(chunks, _LenTok(), 512)
    assert recs, "md 解析後無 chunk 記錄"
    assert any(r["headings"] for r in recs), \
        "真 docling chunk 的 meta.headings 未進記錄(schema 走樣?)"


def test_chunk_records_carry_page_no_pdf(samples, converter):
    """PDF through the real chunker -> the record's page_no is not None (prov chain)."""
    import fitz
    from docling.chunking import HierarchicalChunker
    from src.domain.rag.docling_loader import _refine_chunks_for_token_budget

    pdf_path = samples / "t.pdf"
    with fitz.open() as pdf:
        page = pdf.new_page()
        page.insert_text((72, 72), "SENTINEL provenance text for BL-05")
        pdf.save(str(pdf_path))

    doc = converter.convert(str(pdf_path)).document
    chunks = list(HierarchicalChunker().chunk(doc))
    recs = _refine_chunks_for_token_budget(chunks, _LenTok(), 512)
    assert recs, "PDF 解析後無 chunk 記錄"
    assert any(r["page_no"] == 1 for r in recs), \
        "真 docling chunk 的 prov.page_no 未進記錄(schema 走樣?)"
