"""Alembic environment: resolves the DB URL from config and rewrites autogenerated
migrations to create tables before foreign keys (avoids circular dependencies)."""

import os
import sys
from logging.config import fileConfig

from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context
from alembic.operations.ops import CreateTableOp, CreateForeignKeyOp

# Resolve project root (works in both dev and packaged/Nuitka mode).
_env_file_path = os.path.abspath(__file__)
_alembic_dir = os.path.dirname(_env_file_path)
_migrate_dir = os.path.dirname(_alembic_dir)
_db_dir = os.path.dirname(_migrate_dir)
_project_root = os.path.dirname(_db_dir)

if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

# Change cwd to project root before importing Config so config/config.yaml
# resolves via its relative paths.
_original_cwd = os.getcwd()
os.chdir(_project_root)

from db.db import Base
from src.config.config_manager import Config

config = context.config

# Take the DB URL from config so credentials never live in the migrate folder.
db_conf = Config.get_database_config()
db_url = getattr(db_conf, 'url')
config.set_main_option(
    "sqlalchemy.url", 
    db_url
)

# Use an absolute path for alembic.ini since the working directory was changed above.
if config.config_file_name is not None:
    _alembic_ini_path = os.path.join(_migrate_dir, os.path.basename(config.config_file_name))
    if os.path.exists(_alembic_ini_path):
        fileConfig(_alembic_ini_path)

target_metadata = Base.metadata

# Tables excluded from autogeneration:
# - alembic_version: Alembic's internal tracking table
# - sessions, events, app_states, user_states: Google ADK managed tables
EXCLUDE_TABLES = {
    'alembic_version',
    'sessions',
    'events',
    'app_states',
    'user_states'
}

def process_revision_directives(context, revision, directives):
    """Rewrite the migration so all tables are created first (without foreign keys)
    and all foreign-key constraints are added afterwards, avoiding circular deps."""
    if not directives:
        return

    script = directives[0]
    if not script.upgrade_ops:
        return

    print("🔧 Completely rewriting migration to handle circular dependencies...")

    table_ops = [op for op in script.upgrade_ops.ops if isinstance(op, CreateTableOp)]

    if not table_ops:
        print("  ℹ️ No CreateTable operations found, skipping FK separation")
        return

    upgrade_body = []
    downgrade_body = []
    all_fks = []

    upgrade_body.append('    """Upgrade schema."""')
    upgrade_body.append('    # ### commands auto generated by Alembic - please adjust! ###')

    for op in table_ops:
        print(f"  Processing table: {op.table_name}")

        # Build a create_table statement without foreign keys.
        table_lines = [f"    op.create_table('{op.table_name}',"]

        for col in op.columns:
            if hasattr(col, 'name') and hasattr(col, 'type'):
                col_def = f"    sa.Column('{col.name}', {repr(col.type)}"

                if hasattr(col, 'nullable'):
                    if not col.nullable:
                        col_def += ", nullable=False"
                    elif col.nullable:
                        col_def += ", nullable=True"

                if hasattr(col, 'default') and col.default is not None:
                    col_def += f", default={repr(col.default)}"

                if hasattr(col, 'server_default') and col.server_default is not None:
                    col_def += f", server_default={repr(col.server_default)}"

                col_def += "),"
                table_lines.append(col_def)

                if hasattr(col, 'foreign_keys') and col.foreign_keys:
                    for fk in col.foreign_keys:
                        try:
                            target_col = fk.column
                            target_table = target_col.table.name
                            target_column = target_col.name
                            ondelete = getattr(fk, 'ondelete', None)

                            all_fks.append({
                                'name': f"fk_{op.table_name}_{col.name}",
                                'source_table': op.table_name,
                                'referent_table': target_table,
                                'local_cols': [col.name],
                                'remote_cols': [target_column],
                                'ondelete': ondelete
                            })
                            print(f"    🔗 Collected FK: {op.table_name}.{col.name} -> {target_table}.{target_column}")
                        except Exception as e:
                            print(f"    ⚠️ Error processing FK: {e}")
            else:
                print(f"    ⚠️ Skipping column without name/type attributes")

        # Preserve non-foreign-key constraints (primary key, unique).
        constraints = getattr(op, 'kw', {}).get('constraints', [])
        for constraint in constraints:
            constraint_type = type(constraint).__name__
            if 'ForeignKey' not in constraint_type:
                if 'PrimaryKey' in constraint_type:
                    cols = ', '.join([f"'{col}'" for col in constraint.columns.keys()])
                    table_lines.append(f"    sa.PrimaryKeyConstraint({cols})")
                elif 'Unique' in constraint_type:
                    cols = ', '.join([f"'{col}'" for col in constraint.columns.keys()])
                    name = getattr(constraint, 'name', '')
                    if name:
                        table_lines.append(f"    sa.UniqueConstraint({cols}, name='{name}')")
                    else:
                        table_lines.append(f"    sa.UniqueConstraint({cols})")
        
        table_lines.append("    )")
        upgrade_body.extend(table_lines)
    
    other_ops = [op for op in script.upgrade_ops.ops if not isinstance(op, CreateTableOp)]
    for op in other_ops:
        if hasattr(op, '__class__') and 'Index' in op.__class__.__name__:
            upgrade_body.append(f"    # Index operation: {op}")

    # Add foreign-key constraints after all tables exist.
    if all_fks:
        print(f"  🔗 Adding {len(all_fks)} foreign key constraints:")
        for fk in all_fks:
            print(f"    - {fk['source_table']}.{fk['local_cols'][0]} -> {fk['referent_table']}.{fk['remote_cols'][0]}")
            
            ondelete_part = ""
            if fk['ondelete']:
                ondelete_part = f", ondelete='{fk['ondelete']}'"
            
            fk_line = (f"    op.create_foreign_key('{fk['name']}', '{fk['source_table']}', "
                      f"'{fk['referent_table']}', {fk['local_cols']}, {fk['remote_cols']}{ondelete_part})")
            upgrade_body.append(fk_line)
    
    upgrade_body.append("    # ### end Alembic commands ###")

    downgrade_body.append('    """Downgrade schema."""')
    downgrade_body.append('    # ### commands auto generated by Alembic - please adjust! ###')

    # Drop tables in reverse order to respect dependencies.
    for op in reversed(table_ops):
        downgrade_body.append(f"    op.drop_table('{op.table_name}')")

    downgrade_body.append("    # ### end Alembic commands ###")

    new_upgrade = "\n".join(upgrade_body)
    new_downgrade = "\n".join(downgrade_body)

    script.upgrade_ops_text = new_upgrade
    script.downgrade_ops_text = new_downgrade
    
    print(f"🎉 Migration completely rewritten: {len(table_ops)} tables, {len(all_fks)} deferred FKs")

def include_object(object, name, type_, reflected, compare_to):
    """Exclude EXCLUDE_TABLES from autogeneration."""
    if type_ == "table" and name in EXCLUDE_TABLES:
        return False
    return True

def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (URL only, no Engine/DBAPI needed)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        process_revision_directives=process_revision_directives,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode (create an Engine and bind a connection)."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            process_revision_directives=process_revision_directives,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
