
import os
import sys
from logging.config import fileConfig

from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context
from alembic.operations.ops import CreateTableOp, CreateForeignKeyOp

# Add the project root to Python path
# Support both development mode and packaged mode (Nuitka)
# Path: db/migrate/alembic/env.py -> db/migrate/alembic -> db/migrate -> db -> project_root
_env_file_path = os.path.abspath(__file__)  # /project/db/migrate/alembic/env.py
_alembic_dir = os.path.dirname(_env_file_path)  # /project/db/migrate/alembic
_migrate_dir = os.path.dirname(_alembic_dir)     # /project/db/migrate
_db_dir = os.path.dirname(_migrate_dir)          # /project/db
_project_root = os.path.dirname(_db_dir)         # /project

# Check if we're running from packaged executable
# In that case, project modules should already be in sys.path
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

# CRITICAL: Change working directory to project root BEFORE importing Config
# This ensures config/config.yaml can be found with relative paths
_original_cwd = os.getcwd()
os.chdir(_project_root)

# Import your models
from db.db import Base
from src.config.config_manager import Config

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Override the sqlalchemy.url with the one from your config
# This ensures we always use the correct database URL from config/config.yaml
# and never expose credentials in the migrate folder
db_conf = Config.get_database_config()
db_url = getattr(db_conf, 'url')
config.set_main_option(
    "sqlalchemy.url", 
    db_url
)

# Interpret the config file for Python logging.
# This line sets up loggers basically.
# NOTE: Use absolute path for alembic.ini since we changed working directory
if config.config_file_name is not None:
    _alembic_ini_path = os.path.join(_migrate_dir, os.path.basename(config.config_file_name))
    if os.path.exists(_alembic_ini_path):
        fileConfig(_alembic_ini_path)

# add your model's MetaData object here
# for 'autogenerate' support
target_metadata = Base.metadata

# Tables to exclude from autogeneration
# - alembic_version: Alembic's internal tracking table
# - sessions, events, app_states, user_states: Google ADK managed tables
EXCLUDE_TABLES = {
    'alembic_version',
    'sessions',
    'events',
    'app_states',
    'user_states'
}

def process_revision_directives(context, revision, directives):
    """
    完全重寫遷移以解決循環依賴問題
    
    這個函數會完全重寫遷移文件內容，確保：
    1. 先創建所有表（不帶任何外鍵約束）
    2. 然後添加所有外鍵約束
    """
    if not directives:
        return
    
    script = directives[0]
    if not script.upgrade_ops:
        return
    
    print("🔧 Completely rewriting migration to handle circular dependencies...")
    
    # 檢查是否有 CreateTable 操作
    table_ops = [op for op in script.upgrade_ops.ops if isinstance(op, CreateTableOp)]
    
    if not table_ops:
        print("  ℹ️ No CreateTable operations found, skipping FK separation")
        return
    
    # 重寫腳本內容
    upgrade_body = []
    downgrade_body = []
    all_fks = []
    
    # 添加頭部註釋
    upgrade_body.append('    """Upgrade schema."""')
    upgrade_body.append('    # ### commands auto generated by Alembic - please adjust! ###')
    
    # 處理每個表創建操作
    for op in table_ops:
        print(f"  � Processing table: {op.table_name}")
        
        # 構建乾淨的表創建語句（沒有外鍵）
        table_lines = [f"    op.create_table('{op.table_name}',"]
        
        # 添加列（檢查並移除外鍵）
        for col in op.columns:
            # 安全檢查屬性存在性
            if hasattr(col, 'name') and hasattr(col, 'type'):
                col_def = f"    sa.Column('{col.name}', {repr(col.type)}"
                
                if hasattr(col, 'nullable'):
                    if not col.nullable:
                        col_def += ", nullable=False"
                    elif col.nullable:
                        col_def += ", nullable=True"
                
                if hasattr(col, 'default') and col.default is not None:
                    col_def += f", default={repr(col.default)}"
                
                if hasattr(col, 'server_default') and col.server_default is not None:
                    col_def += f", server_default={repr(col.server_default)}"
                
                col_def += "),"
                table_lines.append(col_def)
                
                # 檢查並收集外鍵約束
                if hasattr(col, 'foreign_keys') and col.foreign_keys:
                    for fk in col.foreign_keys:
                        try:
                            target_col = fk.column
                            target_table = target_col.table.name
                            target_column = target_col.name
                            ondelete = getattr(fk, 'ondelete', None)
                            
                            all_fks.append({
                                'name': f"fk_{op.table_name}_{col.name}",
                                'source_table': op.table_name,
                                'referent_table': target_table,
                                'local_cols': [col.name],
                                'remote_cols': [target_column],
                                'ondelete': ondelete
                            })
                            print(f"    🔗 Collected FK: {op.table_name}.{col.name} -> {target_table}.{target_column}")
                        except Exception as e:
                            print(f"    ⚠️ Error processing FK: {e}")
            else:
                # 跳過無法處理的列
                print(f"    ⚠️ Skipping column without name/type attributes")
        
        # 添加非外鍵約束
        constraints = getattr(op, 'kw', {}).get('constraints', [])
        for constraint in constraints:
            constraint_type = type(constraint).__name__
            if 'ForeignKey' not in constraint_type:
                # 保留非外鍵約束
                if 'PrimaryKey' in constraint_type:
                    cols = ', '.join([f"'{col}'" for col in constraint.columns.keys()])
                    table_lines.append(f"    sa.PrimaryKeyConstraint({cols})")
                elif 'Unique' in constraint_type:
                    cols = ', '.join([f"'{col}'" for col in constraint.columns.keys()])
                    name = getattr(constraint, 'name', '')
                    if name:
                        table_lines.append(f"    sa.UniqueConstraint({cols}, name='{name}')")
                    else:
                        table_lines.append(f"    sa.UniqueConstraint({cols})")
        
        table_lines.append("    )")
        upgrade_body.extend(table_lines)
    
    # 添加其他操作（索引等）
    other_ops = [op for op in script.upgrade_ops.ops if not isinstance(op, CreateTableOp)]
    for op in other_ops:
        if hasattr(op, '__class__') and 'Index' in op.__class__.__name__:
            # 這是創建索引操作
            upgrade_body.append(f"    # Index operation: {op}")
    
    # 添加外鍵約束
    if all_fks:
        print(f"  🔗 Adding {len(all_fks)} foreign key constraints:")
        for fk in all_fks:
            print(f"    - {fk['source_table']}.{fk['local_cols'][0]} -> {fk['referent_table']}.{fk['remote_cols'][0]}")
            
            ondelete_part = ""
            if fk['ondelete']:
                ondelete_part = f", ondelete='{fk['ondelete']}'"
            
            fk_line = (f"    op.create_foreign_key('{fk['name']}', '{fk['source_table']}', "
                      f"'{fk['referent_table']}', {fk['local_cols']}, {fk['remote_cols']}{ondelete_part})")
            upgrade_body.append(fk_line)
    
    upgrade_body.append("    # ### end Alembic commands ###")
    
    # 構建 downgrade 操作
    downgrade_body.append('    """Downgrade schema."""')
    downgrade_body.append('    # ### commands auto generated by Alembic - please adjust! ###')
    
    # 倒序刪除表
    for op in reversed(table_ops):
        downgrade_body.append(f"    op.drop_table('{op.table_name}')")
    
    downgrade_body.append("    # ### end Alembic commands ###")
    
    # 重寫腳本
    new_upgrade = "\n".join(upgrade_body)
    new_downgrade = "\n".join(downgrade_body)
    
    # 完全替換腳本內容
    script.upgrade_ops_text = new_upgrade
    script.downgrade_ops_text = new_downgrade
    
    print(f"🎉 Migration completely rewritten: {len(table_ops)} tables, {len(all_fks)} deferred FKs")

def include_object(object, name, type_, reflected, compare_to):
    """
    Determine whether an object should be included in the autogeneration process.
    """
    if type_ == "table" and name in EXCLUDE_TABLES:
        return False
    return True

def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        process_revision_directives=process_revision_directives,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            process_revision_directives=process_revision_directives,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
